image: golang:latest

variables:
  REPO_NAME: git.openschubla.de/tilman/bvbwarnbot

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - go get ./...

stages:
  - test
  - build-go
  - build-docker

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build-go
  script:
    - go build -race -ldflags "-extldflags '-static'" -o bvbwarnbot-telegram $REPO_NAME/cmd/bvbwarnbot-telegram
  artifacts:
    paths:
      - bvbwarnbot-telegram

docker:
  stage: build-docker
  before_script: []
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest
